<template>
    <div>
        <h1 class="text-center mt-4">WELCOME TO THE STOCK MARKET PROJECT</h1>
        <img src="https://d31dn7nfpuwjnm.cloudfront.net/images/valoraciones/0028/0207/bolsa-de-valores-bolsa-j-carlos-romero-.-com.jpg?1503573233" alt="stockmarket" class="rounded mx-auto d-block mt-4 mb-4">
        <hr>
    </div>
</template>

<script>
export default {
    name: 'SubheaderComponent',   
}
</script>
